### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/runbot-addons#143]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] runbot_build_instructions
- [x] runbot_gitlab - #151
- [ ] runbot_pylint
- [ ] runbot_secure
- [ ] runbot_skip_tests
- [x] runbot_travis2docker - By @moylop260 - #148

**Comment by emagdalenaC2i** [comment]
@pedrobaeza you can update this issue:

runbot_gitlab (Done) https://github.com/OCA/runbot-addons/pull/151
runbot_travis2docker (Done) https://github.com/OCA/runbot-addons/pull/148

Also there are some new modules (I don't know if you want to add this modules to the list)

runbot_buildout (PR) https://github.com/OCA/runbot-addons/pull/154
runbot_preseed_database (PR) https://github.com/OCA/runbot-addons/pull/159
runbot_send_email (Done) https://github.com/OCA/runbot-addons/pull/153
runbot_subject_skip (Done) https://github.com/OCA/runbot-addons/pull/152
