### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/runbot-addons#66]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] runbot_pylint
- [ ] runbot_build_instructions #103 
- [ ] runbot_gitlab
- [ ] runbot_skip_tests #104
- [ ] runbot_secure #87
- [x] runbot_website_diplay #99
