### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/runbot-addons#97]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] runbot_build_instructions
- [ ] runbot_gitlab
- [ ] runbot_pylint
- [ ] runbot_secure
- [ ] runbot_skip_tests
- [ ] runbot_travis2docker
